# Example configuration for Restormer starless training
train_dir: ./train_tiles
val_dir: ./val_tiles
output_dir: ./restormer_logs
image_size: 512
batch_size: 4
num_workers: 8
epochs: 150
lr: 0.0002
weight_decay: 0.0
perceptual_weight: 0.1
mixed_precision: true
save_interval: 10
augment: true
